name: 'Create RC hotfix'
description: 'Start from latest RC and create a hotfix branch.'
inputs:
  release:
    description: 'Which release?'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: mathieudutour/github-tag-action@v6.2
      id: tag_version
      with:
        fetch_all_tags: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
    - run: $GITHUB_ACTION_PATH/create-rc-hotfix.sh ${{ needs.tag_version.outputs.previous_version }}
      shell: bash
