on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Bla
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: D3vlock/github-actions/create-rc-hotfix@v1
        with:
          release: '1.2.3'
      - run: echo "bbbb"
        shell: bash
